### ISSUE TITLE
Change Com Password

### ISSUE THREAD

**Issue by juanignacioarano** [sergiss/anviz-protocol#1]
How could i change the COM MODE password ?
I want to change the password on the devices but i do not understand where should i change it on the code of the library.

**Comment by sergiss** [comment]
Hello?
Can you provide more information about the "COM Mode", for example in which section of the product instructions does it appear or can you share a screenshot? 
Best regards

**Comment by juanignacioarano** [comment]
Hello!
![2023-07-26 15_34_44-Window](https://github.com/sergiss/anviz-protocol/assets/105389482/59dd97f9-d66f-4474-ac19-29407edf8cd6)
I want to change that password, but when i change it the communication with the device stop working.

I'm working with a VF30PRO.

**Comment by sergiss** [comment]
Ah! Ok, so you were referring to the communication password. You can do the following:

device.getDeviceInfo1((info)=> {
  info.communicationPassword‎ = 123456;
  info.communicationPasswordLength‎ = 6;
  device.setDeviceInfo1(info);
});

In this code snippet, it retrieves the "DeviceInfo1", and once retrieved, you can set the communication password.

I have not used this feature (setting the communication password), so I can't guarantee that the communication with the device will continue working. But you will always be able to disable it from the web interface, in order to make it work again.

I hope this helps.
Regards.

**Comment by juanignacioarano** [comment]
Once i set the password how could i change the credentials to adapt to the new communication password ?, because when its not the default password i encounter the following error = "Error: ACK Error: 14"

**Comment by sergiss** [comment]
Hello,
The error occurs because the communication is now "encrypted". You'll need to find out how to "decrypt" this information before the library processes it. Regards, closing the thread.
